<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_</name>
   <tag></tag>
   <elementGuidId>3083a2cf-591c-4a8f-98a6-4dcce1b4ad1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='edit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#edit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>92ff2cf2-3516-4798-b699-3afac8275cae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit</value>
      <webElementGuid>902870a1-72c7-45b6-92a5-9f3d6db89eff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-edit</value>
      <webElementGuid>7362a3af-35dc-48ab-aad9-ec6f5526966f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>เเก้ไข </value>
      <webElementGuid>020d1f59-3339-45cb-b5eb-b0ebd8c0f95b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit&quot;)</value>
      <webElementGuid>59ecd4b1-8ff4-4ac8-93dc-e638e144c4f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='edit']</value>
      <webElementGuid>1339f54a-b8d3-49cc-9bd2-8ac0892a90dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='i']/div/div</value>
      <webElementGuid>b47f2474-33bb-4010-b03a-317d55d8ca0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[1]/following::div[5]</value>
      <webElementGuid>80bbfc8f-acbb-4ac2-a4d0-4aba80cad628</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TODO LIST'])[1]/following::div[6]</value>
      <webElementGuid>a840e2e6-8ba4-400b-a22e-08ef61be507e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ลบ'])[1]/preceding::div[1]</value>
      <webElementGuid>ed5cbed0-4844-4d9f-a552-58212adfb6d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'edit', '&quot;', ')')])[1]/preceding::div[2]</value>
      <webElementGuid>bd531483-6815-459c-ba55-39ae32a8505f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='เเก้ไข']/parent::*</value>
      <webElementGuid>9b2f3a4b-78c0-4ec9-851c-fb7c83c9242e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-todo/div/div/div</value>
      <webElementGuid>707394c2-fdc9-49c7-8922-3fa419cd23df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'edit' and (text() = 'เเก้ไข ' or . = 'เเก้ไข ')]</value>
      <webElementGuid>5326179d-84c9-49cb-80c1-a91b3ddad707</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
