<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__1</name>
   <tag></tag>
   <elementGuidId>6fceebb9-71d4-47f7-8a71-947df137b0b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='edit-i']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.btn-save</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>952a531a-8583-46e2-90e9-14753a18ab98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-save</value>
      <webElementGuid>0605625f-154c-4783-9727-9f96a826abaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>บันทึก</value>
      <webElementGuid>65a1983a-34c4-490e-be2f-478eafa7e27c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-i&quot;)/div[@class=&quot;btn-control&quot;]/div[@class=&quot;btn-save&quot;]</value>
      <webElementGuid>78822254-ed83-409d-824a-8bf0e094087c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-i']/div/div</value>
      <webElementGuid>e4db319c-02df-472c-be80-9b962facbb87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[1]/following::div[5]</value>
      <webElementGuid>cedb6463-0c03-4bd4-b903-8e4689adba5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TODO LIST'])[1]/following::div[6]</value>
      <webElementGuid>5ffd3dd9-fea7-488d-8fe9-a62b1f665cff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='บันทึก']/parent::*</value>
      <webElementGuid>da12bee6-0f5d-4052-8146-77c493cb2cf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-todo/div/div/div</value>
      <webElementGuid>cefd7694-8da6-448a-83cb-ae2ff60deecd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'บันทึก' or . = 'บันทึก')]</value>
      <webElementGuid>1518fe13-2cb4-44b5-8372-3c6b0556f9b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
