<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_TODO LISTAdd2-3-66 go</name>
   <tag></tag>
   <elementGuidId>95f36536-0fdf-4bf0-a252-2ba424cdb05a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.card</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3c18f5e8-b3a0-49d9-91d9-e592aeb1fa90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card</value>
      <webElementGuid>bf230427-ba19-48b5-b88c-ae8b48350909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TODO LISTAdd2-3-66 goเเก้ไข ลบ</value>
      <webElementGuid>21a19bd5-69cc-4945-8d87-7e8629ef303d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/div[@class=&quot;card&quot;]</value>
      <webElementGuid>c1df09f0-8e04-4a5d-b9b4-854f7f11c00a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div</value>
      <webElementGuid>b5d79dc3-62fe-429c-a445-1467ff681670</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'TODO LISTAdd2-3-66 goเเก้ไข ลบ' or . = 'TODO LISTAdd2-3-66 goเเก้ไข ลบ')]</value>
      <webElementGuid>220afdf3-7446-49c7-b996-8b48795998a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
